stripe:
  secret_key:
    ${STRIPE_SECRET_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration:
    time: 9000000

spring:
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update